# -*- coding: utf-8 -*-
"""Week_7_Similar_Images_Function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bB2aIIBHKdtvFEJRZykkoZwDPfmd01Vl

# Week 7: Find Similar Images

Runtime: changed runtime type to GPU

Files setting: Mount to Google Drive
"""

# if not done so, mount your drive
from google.colab import drive
drive.mount('/content/drive')

import os
import matplotlib.pyplot as plt
import random

data_dir = '/content/drive/My Drive/Junior/CS121/artData/small_25_100_data'

# Displays random images of a certain style
# style: the predicted style (does not have to be a string! Can come straight from predictor)
# num_images: The number of images to get
# Note: Right now, it displays using pyplot. The output can be easily changed to be whatever format we will need for front end

def get_similar(style, num_images): 
  class_folder = data_dir + "/" + str(style)

  sim_images = []

  for root, dir, files in os.walk(class_folder):
    while len(sim_images) < num_images:
      img_name = random.choice(files)
      if img_name not in sim_images:
        sim_images.append(img_name)
        img = plt.imread(class_folder + "/" + random.choice(files))
        show = plt.imshow(img)
        plt.show()

get_similar("Ukiyo-e", 3)